/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import BaseDatos.DAOInstituto2;
import ClasesBase.Curso;
import ClasesBase.Evento;
import ClasesBase.Instituto;
import ClasesBase.Modulo;
import Usuarios.Profesor;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author abilius
 */
public class CalendarioProfesor extends javax.swing.JFrame {

    /**
     * Creates new form jCalendario
     */
    int xMouse;
    int yMouse;
    Instituto insti;
    Profesor profe;
    String[] cabecera = new String[5];

    public CalendarioProfesor(Profesor p, Instituto i) {
        initComponents();
        this.insti = i;
        this.profe = p;
        cabecera[0] = "Modulo";
        cabecera[1] = "Curso";
        cabecera[2] = "Ano";//Que alguien cambie la n que no tengo la que va antes de la o XD
        cabecera[3] = "Fecha";
        cabecera[4] = "Mensaje";
        jTable1.setModel(new DefaultTableModel(obtenerEventos(), cabecera));
        for (int j = 0; j < p.getArrayListModulosImpartidos().size(); j++) {

            Modulo m = p.getArrayListModulosImpartidos().get(j);

            ArrayList<Curso> cursos;
            try {
                cursos = DAOInstituto2.instancia().getCursosdeProfesor(p.getNombre(), i);

                jComboBoxModulos.addItem(m.toString() + " " + cursos.get(j).getNombre() + " " + cursos.get(j).getAnno());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error con la base de datos", "Inicio", JOptionPane.WARNING_MESSAGE);
            }

        }

    }

    class jPanelGardient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(221, 0, 255);
            Color color2 = new Color(255, 162, 0);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    public CalendarioProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =  new jPanelGardient();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCalendar = new com.toedter.calendar.JCalendar();
        jButtonNuevoEvento = new javax.swing.JButton();
        jTextFieldMensaje = new javax.swing.JTextField();
        jComboBoxModulos = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modulo", "Curso", "Ano", "Fecha", "Mensaje"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 449, 625, 124));
        jPanel1.add(jCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 170, 426, 261));

        jButtonNuevoEvento.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNuevoEvento.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButtonNuevoEvento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevoEvento.setText("CrearNuevoEvento");
        jButtonNuevoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoEventoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 319, 159, -1));

        jTextFieldMensaje.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jTextFieldMensaje.setText("Nombre del evento");
        jPanel1.add(jTextFieldMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 256, 182, -1));

        jPanel1.add(jComboBoxModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 189, 159, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_undo_50px_1.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("x");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calendario Profesor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoEventoActionPerformed

        try {

            Date fecha = jCalendar.getDate();//Obtenemos la fecha seleccionada por el usuario
            String mensaje = jTextFieldMensaje.getText();//Obtenemos tambien el mensaje
            Evento e = new Evento(mensaje, fecha);//Creamos el nuevo evento
            //Los cursos estan ordenados en las mismas posiciones que los modulos por lo tanto un curso corresponde a un Modulo
            ArrayList<Curso> cursos = DAOInstituto2.instancia().getCursosdeProfesor(profe.getNombre(), insti);//Obtenemos los cursos de los modulos que tiene asignados un profesor
            Modulo m = insti.getModuloNombre(cursos.get(jComboBoxModulos.getSelectedIndex()), profe.getArrayListModulosImpartidos().get(jComboBoxModulos.getSelectedIndex()).getNombre());//Obtenemos el modulo seleeccionado por el combo box y este lo relacionamos con su curso
            m.annnadirEvento(e);//Creamos el modulo al que annadir el evento

            DAOInstituto2.instancia().anadirEvento(e, profe.getArrayListModulosImpartidos().get(jComboBoxModulos.getSelectedIndex()).getNombre(), cursos.get(jComboBoxModulos.getSelectedIndex()), insti.getNombre());
            //anadimos a la tabla eventos el vevento creado con su modulo, ciclo,fechay mensaje

            //Como mostrar los datos en la tabla
            jTable1.setModel(new DefaultTableModel(obtenerEventos(), cabecera));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error con la base de datos", "Inicio", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_jButtonNuevoEventoActionPerformed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        ProfesorGrafico pr = new ProfesorGrafico(this.profe, this.insti);
        pr.mostrar(this.profe.getNombre());
        pr.setVisible(true);

    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        System.exit(0);        
    }//GEN-LAST:event_jLabel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);      
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarioProfesor().setVisible(true);
            }
        });
    }

    public String[][] obtenerEventos() {

        String eventos[][] = new String[100][5];
        int contador = 0;
        ArrayList<Curso> cursos = null;
        try {
            cursos = DAOInstituto2.instancia().getCursosdeProfesor(profe.getNombre(), insti);//Obtenemos los cursos de los modulos que tiene asignados un profesor
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error con la base de datos", "Inicio", JOptionPane.WARNING_MESSAGE);
        }

        for (int i = 0; i < profe.getArrayListModulosImpartidos().size(); i++) {

            Modulo a = profe.getArrayListModulosImpartidos().get(i);

            for (int j = 0; j < a.getCalendario().size(); j++) {

                eventos[contador][0] = a.getNombre();
                eventos[contador][1] = cursos.get(i).getNombre();
                eventos[contador][2] = cursos.get(i).getAnno() + "";
                eventos[contador][3] = a.getCalendario().get(j).getFecha() + "";
                eventos[contador][4] = a.getCalendario().get(j).getMensaje();
                contador++;

            }
        }

        return eventos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNuevoEvento;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JComboBox<String> jComboBoxModulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMensaje;
    // End of variables declaration//GEN-END:variables
}
