/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import BaseDatos.*;
import ClasesBase.*;
import Usuarios.*;
import Grafico.*;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class InicioSesion extends javax.swing.JFrame {

    private Instituto i;

    /**
     * Creates new form InicioSesionç
     */
    public InicioSesion() {
        initComponents();
    }

    //colorines
    class jPanelGardient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(221, 0, 255);
            Color color2 = new Color(255, 162, 0);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGardient();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTNombreInstituto = new javax.swing.JTextField();
        jTUsuario = new javax.swing.JTextField();
        jPConstrasena = new javax.swing.JPasswordField();
        ButtonEntrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Indica cual es tu instituto");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 682, -1));

        jTNombreInstituto.setBackground(new java.awt.Color(255, 255, 255));
        jTNombreInstituto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jTNombreInstituto.setText("Nombre de instituto");
        jTNombreInstituto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTNombreInstitutoMousePressed(evt);
            }
        });
        jPanel1.add(jTNombreInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 319, -1));

        jTUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jTUsuario.setText("Usuario");
        jTUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTUsuarioMousePressed(evt);
            }
        });
        jTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 319, -1));

        jPConstrasena.setBackground(new java.awt.Color(255, 255, 255));
        jPConstrasena.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jPConstrasena.setText("jkdhasgh jkasdhasdkas");
        jPConstrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPConstrasenaMousePressed(evt);
            }
        });
        jPanel1.add(jPConstrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 319, -1));

        ButtonEntrar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEntrar.setText("Entrar");
        ButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_student_male_50px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 228, -1, -1));

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 6, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_user_50px_3.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_lock_50px_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(682, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntrarActionPerformed
        // TODO add your handling code here:
        String nombreInsti = jTNombreInstituto.getText();
        String nombre = jTUsuario.getText();
        String contra = jPConstrasena.getText();
        ConexionDefault.crearConexion();
        int tipo = DAOInstituto2.instancia().obtenerTipoUsuario(nombre, nombreInsti);
        
        i=DAOInstituto2.instancia().obtenerInstituto(nombreInsti);

        switch (tipo) {

            case 0:
                Administrador admin = DAOInstituto2.instancia().obtenerAdministrador(nombre, nombreInsti);
                if (admin.getContrasenna().equals(contra)) {
                    AdministradorGrafico adm = new AdministradorGrafico(admin,i);//Modificar
                    this.setVisible(false);
                    adm.mostrar(nombre);
                    adm.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Inicio", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case 1:

                Alumno alum = DAOInstituto2.instancia().obtenerAlumno(nombre, nombreInsti);

                if (alum.getContrasenna().equals(contra)) {
                    AlumnoGrafico alG = new AlumnoGrafico(null, true, alum, this);
                    this.setVisible(false);
                    // adm.mostrar();
                    alG.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Inicio", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case 2:
                Profesor prof =  DAOInstituto2.instancia().obtenerProfesor(nombre, nombreInsti);
                if (prof.getContrasenna().equals(contra)){
                    ProfesorGrafico pr = new ProfesorGrafico(null, true, prof, i);
                    this.setVisible(false);
                    pr.setVisible(true);
                }
                
                break;
        }

        //modificar el control de la contrasena
        /*
            if (u instanceof Administrador) {
                if (u.getContra().equals(contra)) {
                    Administrador ad = (Administrador) u;
                    AdministradorGrafico adm = new AdministradorGrafico(null, true, ad, this);
                    this.setVisible(false);
                    adm.mostrar(nombre);
                    adm.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Inicio", JOptionPane.WARNING_MESSAGE);

                }

            }
            if (u instanceof Profesor) {
                if (u.getContra().equals(contra)) {
                    Profesor pro = (Profesor) u;
                    ProfesorGrafico pr = new ProfesorGrafico(null, true, pro, this);
                    this.setVisible(false);
                    //pr.mostrar();
                    pr.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Inicio", JOptionPane.WARNING_MESSAGE);

                }

            }
            if (u instanceof Alumno) {
                if (u.getContra().equals(contra)) {
                    Alumno alu = (Alumno) u;
                    AlumnoGrafico alG = new AlumnoGrafico(null, true, alu, this);
                    this.setVisible(false);
                    // adm.mostrar();
                    alG.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Inicio", JOptionPane.WARNING_MESSAGE);

                }

            }

        }
         */

    }//GEN-LAST:event_ButtonEntrarActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

 System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsuarioActionPerformed

    private void jTNombreInstitutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNombreInstitutoMousePressed




        jTNombreInstituto.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreInstitutoMousePressed

    private void jTUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuarioMousePressed


        jTUsuario.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsuarioMousePressed

    private void jPConstrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPConstrasenaMousePressed

        jPConstrasena.setText("");
    }//GEN-LAST:event_jPConstrasenaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPConstrasena;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTNombreInstituto;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables

}
